server:
  port: 8081

spring:
  application:
    name: apply-credit-card-service
  datasource:
    url: jdbc:mysql://localhost:3306/cc_application?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#Below are the spring-cloud-stream related properties

  cloud:
    stream:
      function:
        definition: publishNewCreditCardEvent
      bindings:
        publishNewCreditCardEvent-out-0:
          destination: CreditCardApplication
          group: creditCard
